/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as CollegeDashboardRouteImport } from './routes/college.dashboard'
import { Route as CollegeFacultyRouteImport } from './routes/college.faculty'
import { Route as CollegeStudentsRouteImport } from './routes/college.students'
import { Route as CompanyApplicationsRouteImport } from './routes/company.applications'
import { Route as CompanyCandidatesRouteImport } from './routes/company.candidates'
import { Route as CompanyDashboardRouteImport } from './routes/company.dashboard'
import { Route as CompanyInternshipsRouteImport } from './routes/company.internships'
import { Route as CompanyOutcomesRouteImport } from './routes/company.outcomes'
import { Route as CompanyProfileRouteImport } from './routes/company.profile'
import { Route as FacultyAssessmentsRouteImport } from './routes/faculty.assessments'
import { Route as FacultyDashboardRouteImport } from './routes/faculty.dashboard'
import { Route as FacultyInternshipsRouteImport } from './routes/faculty.internships'
import { Route as FacultyInterventionsRouteImport } from './routes/faculty.interventions'
import { Route as FacultyProjectsRouteImport } from './routes/faculty.projects'
import { Route as FacultyReadinessRouteImport } from './routes/faculty.readiness'
import { Route as FacultySkillGapsRouteImport } from './routes/faculty.skill-gaps'
import { Route as InternshipsIndexRouteImport } from './routes/internships.index'
import { Route as InternshipsIdRouteImport } from './routes/internships.$id'
import { Route as PassportTokenRouteImport } from './routes/passport.$token'
import { Route as StudentApplicationsRouteImport } from './routes/student.applications'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentPassportRouteImport } from './routes/student.passport'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentProjectsRouteImport } from './routes/student.projects'
import { Route as StudentResumeRouteImport } from './routes/student.resume'
import { Route as StudentRoadmapRouteImport } from './routes/student.roadmap'
import { Route as StudentSkillDevelopmentRouteImport } from './routes/student.skill-development'
import { Route as StudentSkillGapRouteImport } from './routes/student.skill-gap'
import { Route as StudentSkillsRouteImport } from './routes/student.skills'
import { Route as CompanyCandidatesIdRouteImport } from './routes/company.candidates.$id'
import { Route as FacultyStudentsIndexRouteImport } from './routes/faculty.students.index'
import { Route as FacultyStudentsIdRouteImport } from './routes/faculty.students.$id'
import { Route as StudentAssessmentsIndexRouteImport } from './routes/student.assessments.index'
import { Route as StudentAssessmentsIdRouteImport } from './routes/student.assessments.$id'
import { Route as StudentCareersIndexRouteImport } from './routes/student.careers.index'
import { Route as StudentIndustryDemandIndexRouteImport } from './routes/student.industry-demand.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeDashboardRoute = CollegeDashboardRouteImport.update({
  id: '/college/dashboard',
  path: '/college/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeFacultyRoute = CollegeFacultyRouteImport.update({
  id: '/college/faculty',
  path: '/college/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeStudentsRoute = CollegeStudentsRouteImport.update({
  id: '/college/students',
  path: '/college/students',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyApplicationsRoute = CompanyApplicationsRouteImport.update({
  id: '/company/applications',
  path: '/company/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCandidatesRoute = CompanyCandidatesRouteImport.update({
  id: '/company/candidates',
  path: '/company/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyDashboardRoute = CompanyDashboardRouteImport.update({
  id: '/company/dashboard',
  path: '/company/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyInternshipsRoute = CompanyInternshipsRouteImport.update({
  id: '/company/internships',
  path: '/company/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyOutcomesRoute = CompanyOutcomesRouteImport.update({
  id: '/company/outcomes',
  path: '/company/outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyProfileRoute = CompanyProfileRouteImport.update({
  id: '/company/profile',
  path: '/company/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyAssessmentsRoute = FacultyAssessmentsRouteImport.update({
  id: '/faculty/assessments',
  path: '/faculty/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/faculty/dashboard',
  path: '/faculty/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyInternshipsRoute = FacultyInternshipsRouteImport.update({
  id: '/faculty/internships',
  path: '/faculty/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyInterventionsRoute = FacultyInterventionsRouteImport.update({
  id: '/faculty/interventions',
  path: '/faculty/interventions',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyProjectsRoute = FacultyProjectsRouteImport.update({
  id: '/faculty/projects',
  path: '/faculty/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyReadinessRoute = FacultyReadinessRouteImport.update({
  id: '/faculty/readiness',
  path: '/faculty/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultySkillGapsRoute = FacultySkillGapsRouteImport.update({
  id: '/faculty/skill-gaps',
  path: '/faculty/skill-gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsIndexRoute = InternshipsIndexRouteImport.update({
  id: '/internships/',
  path: '/internships/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsIdRoute = InternshipsIdRouteImport.update({
  id: '/internships/$id',
  path: '/internships/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportTokenRoute = PassportTokenRouteImport.update({
  id: '/passport/$token',
  path: '/passport/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentApplicationsRoute = StudentApplicationsRouteImport.update({
  id: '/student/applications',
  path: '/student/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPassportRoute = StudentPassportRouteImport.update({
  id: '/student/passport',
  path: '/student/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProjectsRoute = StudentProjectsRouteImport.update({
  id: '/student/projects',
  path: '/student/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResumeRoute = StudentResumeRouteImport.update({
  id: '/student/resume',
  path: '/student/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoadmapRoute = StudentRoadmapRouteImport.update({
  id: '/student/roadmap',
  path: '/student/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSkillDevelopmentRoute = StudentSkillDevelopmentRouteImport.update({
  id: '/student/skill-development',
  path: '/student/skill-development',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSkillGapRoute = StudentSkillGapRouteImport.update({
  id: '/student/skill-gap',
  path: '/student/skill-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSkillsRoute = StudentSkillsRouteImport.update({
  id: '/student/skills',
  path: '/student/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCandidatesIdRoute = CompanyCandidatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompanyCandidatesRoute,
} as any)
const FacultyStudentsIndexRoute = FacultyStudentsIndexRouteImport.update({
  id: '/faculty/students/',
  path: '/faculty/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyStudentsIdRoute = FacultyStudentsIdRouteImport.update({
  id: '/faculty/students/$id',
  path: '/faculty/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssessmentsIndexRoute = StudentAssessmentsIndexRouteImport.update({
  id: '/student/assessments/',
  path: '/student/assessments/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssessmentsIdRoute = StudentAssessmentsIdRouteImport.update({
  id: '/student/assessments/$id',
  path: '/student/assessments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCareersIndexRoute = StudentCareersIndexRouteImport.update({
  id: '/student/careers/',
  path: '/student/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndustryDemandIndexRoute =
  StudentIndustryDemandIndexRouteImport.update({
    id: '/student/industry-demand/',
    path: '/student/industry-demand/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/college/dashboard': typeof CollegeDashboardRoute
  '/college/faculty': typeof CollegeFacultyRoute
  '/college/students': typeof CollegeStudentsRoute
  '/company/applications': typeof CompanyApplicationsRoute
  '/company/candidates': typeof CompanyCandidatesRouteWithChildren
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/internships': typeof CompanyInternshipsRoute
  '/company/outcomes': typeof CompanyOutcomesRoute
  '/company/profile': typeof CompanyProfileRoute
  '/faculty/assessments': typeof FacultyAssessmentsRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/internships': typeof FacultyInternshipsRoute
  '/faculty/interventions': typeof FacultyInterventionsRoute
  '/faculty/projects': typeof FacultyProjectsRoute
  '/faculty/readiness': typeof FacultyReadinessRoute
  '/faculty/skill-gaps': typeof FacultySkillGapsRoute
  '/internships/$id': typeof InternshipsIdRoute
  '/passport/$token': typeof PassportTokenRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/passport': typeof StudentPassportRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/projects': typeof StudentProjectsRoute
  '/student/resume': typeof StudentResumeRoute
  '/student/roadmap': typeof StudentRoadmapRoute
  '/student/skill-development': typeof StudentSkillDevelopmentRoute
  '/student/skill-gap': typeof StudentSkillGapRoute
  '/student/skills': typeof StudentSkillsRoute
  '/internships/': typeof InternshipsIndexRoute
  '/company/candidates/$id': typeof CompanyCandidatesIdRoute
  '/faculty/students/$id': typeof FacultyStudentsIdRoute
  '/student/assessments/$id': typeof StudentAssessmentsIdRoute
  '/faculty/students/': typeof FacultyStudentsIndexRoute
  '/student/assessments/': typeof StudentAssessmentsIndexRoute
  '/student/careers/': typeof StudentCareersIndexRoute
  '/student/industry-demand/': typeof StudentIndustryDemandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/college/dashboard': typeof CollegeDashboardRoute
  '/college/faculty': typeof CollegeFacultyRoute
  '/college/students': typeof CollegeStudentsRoute
  '/company/applications': typeof CompanyApplicationsRoute
  '/company/candidates': typeof CompanyCandidatesRouteWithChildren
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/internships': typeof CompanyInternshipsRoute
  '/company/outcomes': typeof CompanyOutcomesRoute
  '/company/profile': typeof CompanyProfileRoute
  '/faculty/assessments': typeof FacultyAssessmentsRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/internships': typeof FacultyInternshipsRoute
  '/faculty/interventions': typeof FacultyInterventionsRoute
  '/faculty/projects': typeof FacultyProjectsRoute
  '/faculty/readiness': typeof FacultyReadinessRoute
  '/faculty/skill-gaps': typeof FacultySkillGapsRoute
  '/internships/$id': typeof InternshipsIdRoute
  '/passport/$token': typeof PassportTokenRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/passport': typeof StudentPassportRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/projects': typeof StudentProjectsRoute
  '/student/resume': typeof StudentResumeRoute
  '/student/roadmap': typeof StudentRoadmapRoute
  '/student/skill-development': typeof StudentSkillDevelopmentRoute
  '/student/skill-gap': typeof StudentSkillGapRoute
  '/student/skills': typeof StudentSkillsRoute
  '/internships': typeof InternshipsIndexRoute
  '/company/candidates/$id': typeof CompanyCandidatesIdRoute
  '/faculty/students/$id': typeof FacultyStudentsIdRoute
  '/student/assessments/$id': typeof StudentAssessmentsIdRoute
  '/faculty/students': typeof FacultyStudentsIndexRoute
  '/student/assessments': typeof StudentAssessmentsIndexRoute
  '/student/careers': typeof StudentCareersIndexRoute
  '/student/industry-demand': typeof StudentIndustryDemandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/college/dashboard': typeof CollegeDashboardRoute
  '/college/faculty': typeof CollegeFacultyRoute
  '/college/students': typeof CollegeStudentsRoute
  '/company/applications': typeof CompanyApplicationsRoute
  '/company/candidates': typeof CompanyCandidatesRouteWithChildren
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/internships': typeof CompanyInternshipsRoute
  '/company/outcomes': typeof CompanyOutcomesRoute
  '/company/profile': typeof CompanyProfileRoute
  '/faculty/assessments': typeof FacultyAssessmentsRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/internships': typeof FacultyInternshipsRoute
  '/faculty/interventions': typeof FacultyInterventionsRoute
  '/faculty/projects': typeof FacultyProjectsRoute
  '/faculty/readiness': typeof FacultyReadinessRoute
  '/faculty/skill-gaps': typeof FacultySkillGapsRoute
  '/internships/$id': typeof InternshipsIdRoute
  '/passport/$token': typeof PassportTokenRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/passport': typeof StudentPassportRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/projects': typeof StudentProjectsRoute
  '/student/resume': typeof StudentResumeRoute
  '/student/roadmap': typeof StudentRoadmapRoute
  '/student/skill-development': typeof StudentSkillDevelopmentRoute
  '/student/skill-gap': typeof StudentSkillGapRoute
  '/student/skills': typeof StudentSkillsRoute
  '/internships/': typeof InternshipsIndexRoute
  '/company/candidates/$id': typeof CompanyCandidatesIdRoute
  '/faculty/students/$id': typeof FacultyStudentsIdRoute
  '/student/assessments/$id': typeof StudentAssessmentsIdRoute
  '/faculty/students/': typeof FacultyStudentsIndexRoute
  '/student/assessments/': typeof StudentAssessmentsIndexRoute
  '/student/careers/': typeof StudentCareersIndexRoute
  '/student/industry-demand/': typeof StudentIndustryDemandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/college/dashboard'
    | '/college/faculty'
    | '/college/students'
    | '/company/applications'
    | '/company/candidates'
    | '/company/dashboard'
    | '/company/internships'
    | '/company/outcomes'
    | '/company/profile'
    | '/faculty/assessments'
    | '/faculty/dashboard'
    | '/faculty/internships'
    | '/faculty/interventions'
    | '/faculty/projects'
    | '/faculty/readiness'
    | '/faculty/skill-gaps'
    | '/internships/$id'
    | '/passport/$token'
    | '/student/applications'
    | '/student/dashboard'
    | '/student/passport'
    | '/student/profile'
    | '/student/projects'
    | '/student/resume'
    | '/student/roadmap'
    | '/student/skill-development'
    | '/student/skill-gap'
    | '/student/skills'
    | '/internships/'
    | '/company/candidates/$id'
    | '/faculty/students/$id'
    | '/student/assessments/$id'
    | '/faculty/students/'
    | '/student/assessments/'
    | '/student/careers/'
    | '/student/industry-demand/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/college/dashboard'
    | '/college/faculty'
    | '/college/students'
    | '/company/applications'
    | '/company/candidates'
    | '/company/dashboard'
    | '/company/internships'
    | '/company/outcomes'
    | '/company/profile'
    | '/faculty/assessments'
    | '/faculty/dashboard'
    | '/faculty/internships'
    | '/faculty/interventions'
    | '/faculty/projects'
    | '/faculty/readiness'
    | '/faculty/skill-gaps'
    | '/internships/$id'
    | '/passport/$token'
    | '/student/applications'
    | '/student/dashboard'
    | '/student/passport'
    | '/student/profile'
    | '/student/projects'
    | '/student/resume'
    | '/student/roadmap'
    | '/student/skill-development'
    | '/student/skill-gap'
    | '/student/skills'
    | '/internships'
    | '/company/candidates/$id'
    | '/faculty/students/$id'
    | '/student/assessments/$id'
    | '/faculty/students'
    | '/student/assessments'
    | '/student/careers'
    | '/student/industry-demand'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/college/dashboard'
    | '/college/faculty'
    | '/college/students'
    | '/company/applications'
    | '/company/candidates'
    | '/company/dashboard'
    | '/company/internships'
    | '/company/outcomes'
    | '/company/profile'
    | '/faculty/assessments'
    | '/faculty/dashboard'
    | '/faculty/internships'
    | '/faculty/interventions'
    | '/faculty/projects'
    | '/faculty/readiness'
    | '/faculty/skill-gaps'
    | '/internships/$id'
    | '/passport/$token'
    | '/student/applications'
    | '/student/dashboard'
    | '/student/passport'
    | '/student/profile'
    | '/student/projects'
    | '/student/resume'
    | '/student/roadmap'
    | '/student/skill-development'
    | '/student/skill-gap'
    | '/student/skills'
    | '/internships/'
    | '/company/candidates/$id'
    | '/faculty/students/$id'
    | '/student/assessments/$id'
    | '/faculty/students/'
    | '/student/assessments/'
    | '/student/careers/'
    | '/student/industry-demand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  CollegeDashboardRoute: typeof CollegeDashboardRoute
  CollegeFacultyRoute: typeof CollegeFacultyRoute
  CollegeStudentsRoute: typeof CollegeStudentsRoute
  CompanyApplicationsRoute: typeof CompanyApplicationsRoute
  CompanyCandidatesRoute: typeof CompanyCandidatesRouteWithChildren
  CompanyDashboardRoute: typeof CompanyDashboardRoute
  CompanyInternshipsRoute: typeof CompanyInternshipsRoute
  CompanyOutcomesRoute: typeof CompanyOutcomesRoute
  CompanyProfileRoute: typeof CompanyProfileRoute
  FacultyAssessmentsRoute: typeof FacultyAssessmentsRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyInternshipsRoute: typeof FacultyInternshipsRoute
  FacultyInterventionsRoute: typeof FacultyInterventionsRoute
  FacultyProjectsRoute: typeof FacultyProjectsRoute
  FacultyReadinessRoute: typeof FacultyReadinessRoute
  FacultySkillGapsRoute: typeof FacultySkillGapsRoute
  InternshipsIdRoute: typeof InternshipsIdRoute
  PassportTokenRoute: typeof PassportTokenRoute
  StudentApplicationsRoute: typeof StudentApplicationsRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentPassportRoute: typeof StudentPassportRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentProjectsRoute: typeof StudentProjectsRoute
  StudentResumeRoute: typeof StudentResumeRoute
  StudentRoadmapRoute: typeof StudentRoadmapRoute
  StudentSkillDevelopmentRoute: typeof StudentSkillDevelopmentRoute
  StudentSkillGapRoute: typeof StudentSkillGapRoute
  StudentSkillsRoute: typeof StudentSkillsRoute
  InternshipsIndexRoute: typeof InternshipsIndexRoute
  FacultyStudentsIdRoute: typeof FacultyStudentsIdRoute
  StudentAssessmentsIdRoute: typeof StudentAssessmentsIdRoute
  FacultyStudentsIndexRoute: typeof FacultyStudentsIndexRoute
  StudentAssessmentsIndexRoute: typeof StudentAssessmentsIndexRoute
  StudentCareersIndexRoute: typeof StudentCareersIndexRoute
  StudentIndustryDemandIndexRoute: typeof StudentIndustryDemandIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college/dashboard': {
      id: '/college/dashboard'
      path: '/college/dashboard'
      fullPath: '/college/dashboard'
      preLoaderRoute: typeof CollegeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college/faculty': {
      id: '/college/faculty'
      path: '/college/faculty'
      fullPath: '/college/faculty'
      preLoaderRoute: typeof CollegeFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college/students': {
      id: '/college/students'
      path: '/college/students'
      fullPath: '/college/students'
      preLoaderRoute: typeof CollegeStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/applications': {
      id: '/company/applications'
      path: '/company/applications'
      fullPath: '/company/applications'
      preLoaderRoute: typeof CompanyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/candidates': {
      id: '/company/candidates'
      path: '/company/candidates'
      fullPath: '/company/candidates'
      preLoaderRoute: typeof CompanyCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/dashboard': {
      id: '/company/dashboard'
      path: '/company/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof CompanyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/internships': {
      id: '/company/internships'
      path: '/company/internships'
      fullPath: '/company/internships'
      preLoaderRoute: typeof CompanyInternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/outcomes': {
      id: '/company/outcomes'
      path: '/company/outcomes'
      fullPath: '/company/outcomes'
      preLoaderRoute: typeof CompanyOutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/profile': {
      id: '/company/profile'
      path: '/company/profile'
      fullPath: '/company/profile'
      preLoaderRoute: typeof CompanyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/assessments': {
      id: '/faculty/assessments'
      path: '/faculty/assessments'
      fullPath: '/faculty/assessments'
      preLoaderRoute: typeof FacultyAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/dashboard': {
      id: '/faculty/dashboard'
      path: '/faculty/dashboard'
      fullPath: '/faculty/dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/internships': {
      id: '/faculty/internships'
      path: '/faculty/internships'
      fullPath: '/faculty/internships'
      preLoaderRoute: typeof FacultyInternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/interventions': {
      id: '/faculty/interventions'
      path: '/faculty/interventions'
      fullPath: '/faculty/interventions'
      preLoaderRoute: typeof FacultyInterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/projects': {
      id: '/faculty/projects'
      path: '/faculty/projects'
      fullPath: '/faculty/projects'
      preLoaderRoute: typeof FacultyProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/readiness': {
      id: '/faculty/readiness'
      path: '/faculty/readiness'
      fullPath: '/faculty/readiness'
      preLoaderRoute: typeof FacultyReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/skill-gaps': {
      id: '/faculty/skill-gaps'
      path: '/faculty/skill-gaps'
      fullPath: '/faculty/skill-gaps'
      preLoaderRoute: typeof FacultySkillGapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships/': {
      id: '/internships/'
      path: '/internships'
      fullPath: '/internships/'
      preLoaderRoute: typeof InternshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships/$id': {
      id: '/internships/$id'
      path: '/internships/$id'
      fullPath: '/internships/$id'
      preLoaderRoute: typeof InternshipsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/$token': {
      id: '/passport/$token'
      path: '/passport/$token'
      fullPath: '/passport/$token'
      preLoaderRoute: typeof PassportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/applications': {
      id: '/student/applications'
      path: '/student/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof StudentApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/passport': {
      id: '/student/passport'
      path: '/student/passport'
      fullPath: '/student/passport'
      preLoaderRoute: typeof StudentPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/projects': {
      id: '/student/projects'
      path: '/student/projects'
      fullPath: '/student/projects'
      preLoaderRoute: typeof StudentProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/resume': {
      id: '/student/resume'
      path: '/student/resume'
      fullPath: '/student/resume'
      preLoaderRoute: typeof StudentResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/roadmap': {
      id: '/student/roadmap'
      path: '/student/roadmap'
      fullPath: '/student/roadmap'
      preLoaderRoute: typeof StudentRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/skill-development': {
      id: '/student/skill-development'
      path: '/student/skill-development'
      fullPath: '/student/skill-development'
      preLoaderRoute: typeof StudentSkillDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/skill-gap': {
      id: '/student/skill-gap'
      path: '/student/skill-gap'
      fullPath: '/student/skill-gap'
      preLoaderRoute: typeof StudentSkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/skills': {
      id: '/student/skills'
      path: '/student/skills'
      fullPath: '/student/skills'
      preLoaderRoute: typeof StudentSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/candidates/$id': {
      id: '/company/candidates/$id'
      path: '/$id'
      fullPath: '/company/candidates/$id'
      preLoaderRoute: typeof CompanyCandidatesIdRouteImport
      parentRoute: typeof CompanyCandidatesRoute
    }
    '/faculty/students/': {
      id: '/faculty/students/'
      path: '/faculty/students'
      fullPath: '/faculty/students/'
      preLoaderRoute: typeof FacultyStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/students/$id': {
      id: '/faculty/students/$id'
      path: '/faculty/students/$id'
      fullPath: '/faculty/students/$id'
      preLoaderRoute: typeof FacultyStudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assessments/': {
      id: '/student/assessments/'
      path: '/student/assessments'
      fullPath: '/student/assessments/'
      preLoaderRoute: typeof StudentAssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assessments/$id': {
      id: '/student/assessments/$id'
      path: '/student/assessments/$id'
      fullPath: '/student/assessments/$id'
      preLoaderRoute: typeof StudentAssessmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/careers/': {
      id: '/student/careers/'
      path: '/student/careers'
      fullPath: '/student/careers/'
      preLoaderRoute: typeof StudentCareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/industry-demand/': {
      id: '/student/industry-demand/'
      path: '/student/industry-demand'
      fullPath: '/student/industry-demand/'
      preLoaderRoute: typeof StudentIndustryDemandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompanyCandidatesRouteChildren {
  CompanyCandidatesIdRoute: typeof CompanyCandidatesIdRoute
}

const CompanyCandidatesRouteChildren: CompanyCandidatesRouteChildren = {
  CompanyCandidatesIdRoute: CompanyCandidatesIdRoute,
}

const CompanyCandidatesRouteWithChildren =
  CompanyCandidatesRoute._addFileChildren(CompanyCandidatesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  CollegeDashboardRoute: CollegeDashboardRoute,
  CollegeFacultyRoute: CollegeFacultyRoute,
  CollegeStudentsRoute: CollegeStudentsRoute,
  CompanyApplicationsRoute: CompanyApplicationsRoute,
  CompanyCandidatesRoute: CompanyCandidatesRouteWithChildren,
  CompanyDashboardRoute: CompanyDashboardRoute,
  CompanyInternshipsRoute: CompanyInternshipsRoute,
  CompanyOutcomesRoute: CompanyOutcomesRoute,
  CompanyProfileRoute: CompanyProfileRoute,
  FacultyAssessmentsRoute: FacultyAssessmentsRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyInternshipsRoute: FacultyInternshipsRoute,
  FacultyInterventionsRoute: FacultyInterventionsRoute,
  FacultyProjectsRoute: FacultyProjectsRoute,
  FacultyReadinessRoute: FacultyReadinessRoute,
  FacultySkillGapsRoute: FacultySkillGapsRoute,
  InternshipsIdRoute: InternshipsIdRoute,
  PassportTokenRoute: PassportTokenRoute,
  StudentApplicationsRoute: StudentApplicationsRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentPassportRoute: StudentPassportRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentProjectsRoute: StudentProjectsRoute,
  StudentResumeRoute: StudentResumeRoute,
  StudentRoadmapRoute: StudentRoadmapRoute,
  StudentSkillDevelopmentRoute: StudentSkillDevelopmentRoute,
  StudentSkillGapRoute: StudentSkillGapRoute,
  StudentSkillsRoute: StudentSkillsRoute,
  InternshipsIndexRoute: InternshipsIndexRoute,
  FacultyStudentsIdRoute: FacultyStudentsIdRoute,
  StudentAssessmentsIdRoute: StudentAssessmentsIdRoute,
  FacultyStudentsIndexRoute: FacultyStudentsIndexRoute,
  StudentAssessmentsIndexRoute: StudentAssessmentsIndexRoute,
  StudentCareersIndexRoute: StudentCareersIndexRoute,
  StudentIndustryDemandIndexRoute: StudentIndustryDemandIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
